### ISSUE TITLE
Issue with the tax staying at low 

### ISSUE THREAD

**Issue by ezyhabz** [cadburry6969/cad-tax#2]
Even i have more than the economy tax bracket it only takes low bracket

**Comment by ezyhabz** [comment]
i only changed the percentage of the brackets, thats all then set my money to 2Million which should be on extreme bracket but it only take low bracket

**Comment by cadburry6969** [comment]
Fixed!
https://github.com/cadburry6969/cad-tax/commit/98ed3d3675db5b6256da0aeb139f86e69c81a05a
